/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sydingto;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import sydingto.res.Colors;

/**
 *
 * @author satmaxt
 */
public class MainFrame extends javax.swing.JFrame {

    private Color color;
    private String title = "Home";
    private final ArrayList<JPanel> btnPanels = new ArrayList<>();

    /**
     * Creates new form MainFrame
     * @param username
     */
    public MainFrame(String username) {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        menuHome.setHorizontalAlignment(SwingConstants.CENTER);
        usernameTitle.setText(username);

        MainFrame _that = this;
        btnPanels.add(btnHome);
        btnPanels.add(btnCourse);
        btnPanels.add(btnExercise);
        btnPanels.add(btnResources);
        btnPanels.add(btnSignOut);
        
        headerTitle.setText(title);
        setActivePanel(homePanel, btnHome, title);
        
        btnPanels.forEach(panel -> {
            panel.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseExited(MouseEvent me) {
                    _that.onHoverOutSidebarButton(me);
                }

                @Override
                public void mouseEntered(MouseEvent me) {
                    _that.onHoverSidebarButton(me);
                }
                
            });
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainBG = new javax.swing.JPanel();
        sidebarPanel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        btnHome = new javax.swing.JPanel();
        iconHome = new javax.swing.JLabel();
        menuHome = new javax.swing.JLabel();
        btnCourse = new javax.swing.JPanel();
        iconBook = new javax.swing.JLabel();
        menuCourse = new javax.swing.JLabel();
        btnExercise = new javax.swing.JPanel();
        iconBook1 = new javax.swing.JLabel();
        menuCourse1 = new javax.swing.JLabel();
        btnResources = new javax.swing.JPanel();
        iconBook2 = new javax.swing.JLabel();
        menuCourse2 = new javax.swing.JLabel();
        btnSignOut = new javax.swing.JPanel();
        iconBook3 = new javax.swing.JLabel();
        menuCourse3 = new javax.swing.JLabel();
        headerPanel = new javax.swing.JPanel();
        buttonClose = new javax.swing.JLabel();
        btnAbout = new javax.swing.JLabel();
        buttonMinimize = new javax.swing.JLabel();
        usernameTitle = new javax.swing.JLabel();
        headerTitle = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        coursePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        filter1 = new javax.swing.JComboBox<>();
        filter2 = new javax.swing.JComboBox<>();
        filter3 = new javax.swing.JComboBox<>();
        resourcesPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        filter4 = new javax.swing.JComboBox<>();
        filter5 = new javax.swing.JComboBox<>();
        filter6 = new javax.swing.JComboBox<>();
        exercisePanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        filter7 = new javax.swing.JComboBox<>();
        filter9 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(246, 255, 254));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        mainBG.setBackground(new java.awt.Color(246, 255, 254));

        sidebarPanel.setBackground(new java.awt.Color(0, 223, 191));
        sidebarPanel.setToolTipText("");
        sidebarPanel.setMaximumSize(new java.awt.Dimension(120, 600));
        sidebarPanel.setMinimumSize(new java.awt.Dimension(120, 600));
        sidebarPanel.setPreferredSize(new java.awt.Dimension(120, 600));

        logo.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        logo.setForeground(new java.awt.Color(255, 255, 255));
        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setText("Sydingto");
        logo.setAlignmentX(0.5F);
        logo.setFocusable(false);
        logo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnHome.setBackground(new java.awt.Color(0, 223, 191));
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.setMaximumSize(new java.awt.Dimension(32767, 83));
        btnHome.setMinimumSize(new java.awt.Dimension(0, 83));
        btnHome.setPreferredSize(new java.awt.Dimension(0, 83));
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });
        btnHome.setLayout(new java.awt.GridBagLayout());

        iconHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sydingto/images/Home.png"))); // NOI18N
        iconHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        btnHome.add(iconHome, gridBagConstraints);

        menuHome.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        menuHome.setForeground(new java.awt.Color(255, 255, 255));
        menuHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuHome.setText("Home");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 12;
        btnHome.add(menuHome, gridBagConstraints);

        btnCourse.setBackground(new java.awt.Color(0, 223, 191));
        btnCourse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCourse.setMaximumSize(new java.awt.Dimension(32767, 83));
        btnCourse.setMinimumSize(new java.awt.Dimension(0, 83));
        btnCourse.setPreferredSize(new java.awt.Dimension(0, 83));
        btnCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCourseMouseClicked(evt);
            }
        });
        btnCourse.setLayout(new java.awt.GridBagLayout());

        iconBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sydingto/images/book.png"))); // NOI18N
        iconBook.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        btnCourse.add(iconBook, gridBagConstraints);

        menuCourse.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        menuCourse.setForeground(new java.awt.Color(255, 255, 255));
        menuCourse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuCourse.setText("Course");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 12;
        btnCourse.add(menuCourse, gridBagConstraints);

        btnExercise.setBackground(new java.awt.Color(0, 223, 191));
        btnExercise.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExercise.setMaximumSize(new java.awt.Dimension(32767, 83));
        btnExercise.setMinimumSize(new java.awt.Dimension(0, 83));
        btnExercise.setPreferredSize(new java.awt.Dimension(0, 83));
        btnExercise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExerciseMouseClicked(evt);
            }
        });
        btnExercise.setLayout(new java.awt.GridBagLayout());

        iconBook1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sydingto/images/exercise.png"))); // NOI18N
        iconBook1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        btnExercise.add(iconBook1, gridBagConstraints);

        menuCourse1.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        menuCourse1.setForeground(new java.awt.Color(255, 255, 255));
        menuCourse1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuCourse1.setText("Exercise");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 12;
        btnExercise.add(menuCourse1, gridBagConstraints);

        btnResources.setBackground(new java.awt.Color(0, 223, 191));
        btnResources.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResources.setMaximumSize(new java.awt.Dimension(32767, 83));
        btnResources.setMinimumSize(new java.awt.Dimension(0, 83));
        btnResources.setPreferredSize(new java.awt.Dimension(0, 83));
        btnResources.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResourcesMouseClicked(evt);
            }
        });
        btnResources.setLayout(new java.awt.GridBagLayout());

        iconBook2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sydingto/images/archive.png"))); // NOI18N
        iconBook2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        btnResources.add(iconBook2, gridBagConstraints);

        menuCourse2.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        menuCourse2.setForeground(new java.awt.Color(255, 255, 255));
        menuCourse2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuCourse2.setText("Resources");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 12;
        btnResources.add(menuCourse2, gridBagConstraints);

        btnSignOut.setBackground(new java.awt.Color(0, 223, 191));
        btnSignOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSignOut.setMaximumSize(new java.awt.Dimension(32767, 83));
        btnSignOut.setMinimumSize(new java.awt.Dimension(0, 83));
        btnSignOut.setPreferredSize(new java.awt.Dimension(0, 83));
        btnSignOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignOutMouseClicked(evt);
            }
        });
        btnSignOut.setLayout(new java.awt.GridBagLayout());

        iconBook3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sydingto/images/logout.png"))); // NOI18N
        iconBook3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        btnSignOut.add(iconBook3, gridBagConstraints);

        menuCourse3.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        menuCourse3.setForeground(new java.awt.Color(255, 255, 255));
        menuCourse3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuCourse3.setText("Sign Out");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 12;
        btnSignOut.add(menuCourse3, gridBagConstraints);

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(logo)
                .addContainerGap(26, Short.MAX_VALUE))
            .addComponent(btnCourse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnExercise, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnResources, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSignOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(logo)
                .addGap(26, 26, 26)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnExercise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnResources, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnSignOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(432, 432, 432))
        );

        headerPanel.setBackground(new java.awt.Color(255, 255, 255));
        headerPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(184, 189, 188), 1, true));
        headerPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        headerPanel.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        headerPanel.setMaximumSize(new java.awt.Dimension(624, 32767));
        headerPanel.setMinimumSize(new java.awt.Dimension(624, 0));
        headerPanel.setPreferredSize(new java.awt.Dimension(624, 100));

        buttonClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sydingto/images/btn_close.png"))); // NOI18N
        buttonClose.setToolTipText("Exit");
        buttonClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCloseMouseClicked(evt);
            }
        });

        btnAbout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sydingto/images/btn_about.png"))); // NOI18N
        btnAbout.setToolTipText("About");
        btnAbout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAboutMouseClicked(evt);
            }
        });

        buttonMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sydingto/images/btn_minimize.png"))); // NOI18N
        buttonMinimize.setToolTipText("Minimize");
        buttonMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMinimizeMouseClicked(evt);
            }
        });

        usernameTitle.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        usernameTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usernameTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sydingto/images/user.png"))); // NOI18N
        usernameTitle.setText("satmaxt");

        headerTitle.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        headerTitle.setText("Home");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(headerTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(usernameTitle)
                .addGap(30, 30, 30)
                .addComponent(btnAbout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonMinimize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonClose)
                .addGap(15, 15, 15))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(usernameTitle)
                        .addComponent(headerTitle))
                    .addComponent(buttonClose)
                    .addComponent(btnAbout)
                    .addComponent(buttonMinimize))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(184, 189, 188), 1, true));
        contentPanel.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        contentPanel.setLayout(new java.awt.CardLayout());

        homePanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(184, 189, 188), 2, true));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Lato", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(46, 222, 85));
        jLabel3.setText("10");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 14, 33, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        jLabel4.setText("Course");
        jLabel4.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 12, 0, 14);
        jPanel1.add(jLabel4, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(184, 189, 188), 2, true));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel5.setFont(new java.awt.Font("Lato", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(46, 222, 85));
        jLabel5.setText("5234");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 14, 33, 0);
        jPanel2.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        jLabel6.setText("Total XP");
        jLabel6.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 12, 0, 14);
        jPanel2.add(jLabel6, gridBagConstraints);

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(336, Short.MAX_VALUE))
        );

        contentPanel.add(homePanel, "card2");

        coursePanel.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"JAVA",  new Integer(100),  new Integer(20)},
                {"Vue.js",  new Integer(150),  new Integer(10)},
                {"HTML & CSS",  new Integer(0),  new Integer(39)},
                {"JavaScript",  new Integer(50),  new Integer(5)},
                {"Android",  new Integer(150), null}
            },
            new String [] {
                "Name", "Min XP", "Students"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        filter1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        filter2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        filter3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout coursePanelLayout = new javax.swing.GroupLayout(coursePanel);
        coursePanel.setLayout(coursePanelLayout);
        coursePanelLayout.setHorizontalGroup(
            coursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coursePanelLayout.createSequentialGroup()
                .addGroup(coursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(coursePanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(filter1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(filter3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(filter2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(coursePanelLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        coursePanelLayout.setVerticalGroup(
            coursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coursePanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(coursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filter1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filter3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filter2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(264, Short.MAX_VALUE))
        );

        contentPanel.add(coursePanel, "card3");

        resourcesPanel.setBackground(new java.awt.Color(255, 255, 255));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"drawer component vue", "zip", "50 KB"},
                {"swing dropshadow", "zip", "30 KB"},
                {"swing circle button", "rar", "20 KB"},
                {"awt custom ui", "rar", "30 KB"},
                {"free android ebook", "rar", "10 KB"}
            },
            new String [] {
                "Name", "Type", "Size"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);

        filter4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        filter5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        filter6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout resourcesPanelLayout = new javax.swing.GroupLayout(resourcesPanel);
        resourcesPanel.setLayout(resourcesPanelLayout);
        resourcesPanelLayout.setHorizontalGroup(
            resourcesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resourcesPanelLayout.createSequentialGroup()
                .addGroup(resourcesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(resourcesPanelLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(resourcesPanelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(filter4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(filter6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(filter5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        resourcesPanelLayout.setVerticalGroup(
            resourcesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resourcesPanelLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(resourcesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(filter5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filter6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filter4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(198, Short.MAX_VALUE))
        );

        contentPanel.add(resourcesPanel, "card3");

        exercisePanel.setBackground(new java.awt.Color(255, 255, 255));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"drawer component vue", "zip", "50 KB"},
                {"swing dropshadow", "zip", "30 KB"},
                {"swing circle button", "rar", "20 KB"},
                {"awt custom ui", "rar", "30 KB"},
                {"free android ebook", "rar", "10 KB"}
            },
            new String [] {
                "Name", "Type", "Size"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable3.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTable3);

        filter7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        filter9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout exercisePanelLayout = new javax.swing.GroupLayout(exercisePanel);
        exercisePanel.setLayout(exercisePanelLayout);
        exercisePanelLayout.setHorizontalGroup(
            exercisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exercisePanelLayout.createSequentialGroup()
                .addGroup(exercisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(exercisePanelLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(exercisePanelLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(filter7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(filter9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        exercisePanelLayout.setVerticalGroup(
            exercisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exercisePanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(exercisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(filter9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filter7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(264, Short.MAX_VALUE))
        );

        contentPanel.add(exercisePanel, "card3");

        javax.swing.GroupLayout mainBGLayout = new javax.swing.GroupLayout(mainBG);
        mainBG.setLayout(mainBGLayout);
        mainBGLayout.setHorizontalGroup(
            mainBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainBGLayout.createSequentialGroup()
                .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(mainBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        mainBGLayout.setVerticalGroup(
            mainBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainBGLayout.createSequentialGroup()
                .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(mainBGLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(mainBG);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_buttonCloseMouseClicked

    private void btnAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseClicked
        AboutFrame about = new AboutFrame();
        about.setVisible(true);
    }//GEN-LAST:event_btnAboutMouseClicked

    private void buttonMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMinimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_buttonMinimizeMouseClicked

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        setActivePanel(homePanel, btnHome, "Home");
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseMouseClicked
        setActivePanel(coursePanel, btnCourse, "Course");
    }//GEN-LAST:event_btnCourseMouseClicked

    private void btnExerciseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExerciseMouseClicked
        setActivePanel(exercisePanel, btnExercise, "Exercise");
    }//GEN-LAST:event_btnExerciseMouseClicked

    private void btnResourcesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResourcesMouseClicked
        setActivePanel(resourcesPanel, btnResources, "Resources");
    }//GEN-LAST:event_btnResourcesMouseClicked

    private void btnSignOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignOutMouseClicked
        this.dispose();
        LoginFrame lf = new LoginFrame();
        lf.setVisible(true);
    }//GEN-LAST:event_btnSignOutMouseClicked
    
    private void setActivePanel(JPanel panel, JPanel btn, String title) {
        setHeaderTitle(title);
        contentPanel.removeAll();
        contentPanel.repaint();
        contentPanel.revalidate();
        
        contentPanel.add(panel);
        contentPanel.repaint();
        contentPanel.revalidate();
        resetColorSidebar();
        btn.setBackground(Colors.PRIMARY_COLOR_HOVER);
        color = Colors.PRIMARY_COLOR_HOVER;
    }

    private void resetColorSidebar() {
        btnPanels.forEach(btn -> {
            btn.setBackground(Colors.PRIMARY_COLOR);
        });
    }

    private void setHeaderTitle(String title) {
        this.title = title;
        headerTitle.setText(this.title);
    }
    
    private void onHoverOutSidebarButton(java.awt.event.MouseEvent evt) {
        evt.getComponent().setBackground(color);
    }
    
    private void onHoverSidebarButton(java.awt.event.MouseEvent evt) {
        color = evt.getComponent().getBackground();
        evt.getComponent().setBackground(Colors.PRIMARY_COLOR_HOVER);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame("satmaxt").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAbout;
    private javax.swing.JPanel btnCourse;
    private javax.swing.JPanel btnExercise;
    private javax.swing.JPanel btnHome;
    private javax.swing.JPanel btnResources;
    private javax.swing.JPanel btnSignOut;
    private javax.swing.JLabel buttonClose;
    private javax.swing.JLabel buttonMinimize;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel coursePanel;
    private javax.swing.JPanel exercisePanel;
    private javax.swing.JComboBox<String> filter1;
    private javax.swing.JComboBox<String> filter2;
    private javax.swing.JComboBox<String> filter3;
    private javax.swing.JComboBox<String> filter4;
    private javax.swing.JComboBox<String> filter5;
    private javax.swing.JComboBox<String> filter6;
    private javax.swing.JComboBox<String> filter7;
    private javax.swing.JComboBox<String> filter9;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel headerTitle;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel iconBook;
    private javax.swing.JLabel iconBook1;
    private javax.swing.JLabel iconBook2;
    private javax.swing.JLabel iconBook3;
    private javax.swing.JLabel iconHome;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel mainBG;
    private javax.swing.JLabel menuCourse;
    private javax.swing.JLabel menuCourse1;
    private javax.swing.JLabel menuCourse2;
    private javax.swing.JLabel menuCourse3;
    private javax.swing.JLabel menuHome;
    private javax.swing.JPanel resourcesPanel;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JLabel usernameTitle;
    // End of variables declaration//GEN-END:variables
}
